spring:
    application:
        name: order-service

    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}

    config:
        import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

    autoconfigure:
        exclude:
            - net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration

logging:
    structured:
        format:
            console: logstash
            file: logstash
    file:
        name: ${OBSERVABILITY_LOG_FILE:../logs/order-service.json}
