apiVersion: 1

datasources:
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://ecommerce-prometheus:9090 # Updated to match your docker container name
      isDefault: true
      jsonData:
          httpMethod: POST
          # LINK: Allows you to jump from an exemplar in a metric chart directly to its Tempo Trace
          exemplarTraceIdDestinations:
              - datasourceUid: tempo
                name: traceID

    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://ecommerce-tempo:3200 # Updated to match your docker container name
      jsonData:
          httpMethod: GET
          # LINK: Enables the automated cross-service dependency node maps inside Tempo
          serviceMap:
              datasourceUid: prometheus
          # LINK: Adds a "View Metrics" button inside Tempo span details to see app health
          nodeGraph:
              enabled: true
          tracesToMetrics:
              datasourceUid: prometheus
              spanStartTimeShift: "-5m"
              spanEndTimeShift: "5m"
              tags: [{ key: "service.name", value: "service" }]
              queries:
                  - name: "Application Metrics"
                    query: 'sum(rate(http_server_requests_seconds_count{service="$service"}[5m]))'
