server:
    port: 8888

spring:
    application:
        name: config-server

    cloud:
        config:
            server:
                git:
                    uri: https://github.com/pepetibalaji/ecommerce-config-repo
                    default-label: main
                    clone-on-start: true

management:
    endpoints:
        web:
            exposure:
                # 2. Add 'encrypt' and 'decrypt' to the exposed management endpoints
                include: health,info,refresh,prometheus,encrypt,decrypt
    endpoint:
        health:
            show-details: always

logging:
    structured:
        format:
            console: logstash
            file: logstash
    file:
        name: ${OBSERVABILITY_LOG_FILE:../logs/config-server.json}
